# Generated by Django 3.2.9 on 2024-03-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220427_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='amount',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='client',
            name='emailid',
            field=models.CharField(default=1000, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default=123, max_length=250),
            preserve_default=False,
        ),
    ]
