# Generated by Django 3.2.9 on 2024-03-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20240308_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofloan', models.CharField(max_length=250)),
                ('rateofinterest', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
