# Generated by Django 3.2.9 on 2024-03-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='accout_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
