# Generated by Django 3.2.9 on 2024-03-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customerrequest_accout_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerrequest',
            old_name='accout_id',
            new_name='account_id',
        ),
    ]
