# Generated by Django 3.2.9 on 2024-03-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_account_open_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='branch',
        ),
        migrations.AddField(
            model_name='transfer',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transfer',
            name='fromaccno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transfer',
            name='toaccno',
            field=models.IntegerField(default=0),
        ),
    ]
