# Generated by Django 3.2.9 on 2024-03-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20240309_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='typeofsubservice',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
